apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lu44o9155-nodejs
  janus-idp.io/tekton: lu44o9155-nodejs
  backstage.io/kubernetes-id: lu44o9155-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lu44o9155-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
